# Nombre de la aplicación
spring.application.name=CampusFood


# Configuración de base de datos MySQL (por ahora para entorno local)
# Usar credenciales por defecto o variables de entorno
spring.datasource.url=jdbc:mysql://localhost:3306/campusfood?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Variables personalizadas del sistema
# Dominio de correo permitido para registro
campusfood.allowed.email.domain=${CAMPUSFOOD_ALLOWED_EMAIL_DOMAIN:utp.edu.pe}

# Configuración de Thymeleaf (útil para desarrollo)
spring.thymeleaf.cache=false
